In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cpu


In [3]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

In [4]:
a = torch.empty(2,3)

In [5]:
a

tensor([[-2.5779e+10,  9.7390e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [6]:
type(a)

torch.Tensor

In [7]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])